### ISSUE TITLE
请问为何无法加载成功

### ISSUE THREAD

**Issue by guoyi8** [m80126colin/hexo-tag-owl#1]
提示：
ERROR Plugin load failed: hexo-tag-owl
ReferenceError: hexo is not defined
    at Object.<anonymous> (F:\GitHub\blog\node_modules\hexo-tag-owl\images.js:1:77)

正常在站点配置中加载插件，在md文本中引入例子中的  {% owl-bilibili av247371 %}

hexo g编译时报出上述错误，谢谢能帮忙解答看一下~

**Comment by m80126colin** [comment]
因為 hexo 換了 3.0 這個還是 2.x 時代的，我會處理他的，感謝。
