### ISSUE TITLE
Mobile compatibility for Tencent and Tudou

### ISSUE THREAD

**Issue by trinketmage** [m80126colin/hexo-tag-owl#7]
Hi,
I can see on your demo page that you are embedding some of the videos with format.swf, it makes thoses videos unreadable on mobile for Tencent and Tudou. Do you think it's possible to make a embed with a player like Youku for Tencent and Tudou please ?

**Comment by xzblog** [comment]
我使用该插件，也发现在移动端都播放不了呀！
